services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: false

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/ccc3001/nomad_distro_termplate_1/jupyter:main

keycloak:
  server_url: 'http://keycloak:8080/auth/'
  public_server_url: 'http://192.0.2.1/keycloak/auth/'
  realm_name: nomad
  username: 'admin'
  password: 'password'
  
meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enable: false

logtransfere:
 enabled: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
